{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "c19c4b52-dacb-4af9-ae22-faece40eda67",
   "metadata": {},
   "outputs": [],
   "source": [
    "#!/usr/bin/env python3\n",
    "\"\"\"\n",
    "IIT07 Bus Route Display — Interactive, colorful simulation\n",
    "\"\"\"\n",
    "\n",
    "import tkinter as tk\n",
    "from tkinter import ttk\n",
    "import time\n",
    "import math\n",
    "\n",
    "# ---------------- Configuration ----------------\n",
    "BUS_NAME = \"Bus IIT07\"\n",
    "STOP_NAMES = [\n",
    "    \"IIT MGCL Library\",\n",
    "    \"IIT Century Gate\",\n",
    "    \"Roorkee Bus Stand\",\n",
    "    \"SDM Chauk\",\n",
    "    \"Cownpore Chauk\",\n",
    "    \"Delhi Road\",\n",
    "    \"APJ Chauk\",\n",
    "    \"Manglaur Bus Stop\",\n",
    "    \"Upper Ganga Bridge\",\n",
    "    \"Devband\"\n",
    "]\n",
    "\n",
    "# Visual layout\n",
    "CANVAS_W = 1920\n",
    "CANVAS_H = 500\n",
    "MARGIN_X = 100\n",
    "LINE_Y = 250\n",
    "DOT_RADIUS = 12\n",
    "LABEL_Y = LINE_Y + 35\n",
    "\n",
    "# Route details\n",
    "DIST_BETWEEN_STOPS_M = 2000  # 2 km\n",
    "NUM_STOPS = len(STOP_NAMES)\n",
    "TOTAL_ROUTE_M = DIST_BETWEEN_STOPS_M * (NUM_STOPS - 1)\n",
    "\n",
    "# Simulation parameters\n",
    "BASE_SPEED_KMPH = 120.0\n",
    "UPDATE_INTERVAL_MS = 40\n",
    "\n",
    "PIXEL_ROUTE_LENGTH = CANVAS_W - 2 * MARGIN_X\n",
    "PIXELS_PER_M = PIXEL_ROUTE_LENGTH / TOTAL_ROUTE_M\n",
    "\n",
    "# ---------------- Bus State ----------------\n",
    "bus = {\n",
    "    \"distance_m\": 0.0,\n",
    "    \"speed_kmph\": BASE_SPEED_KMPH,\n",
    "    \"paused\": False,\n",
    "}\n",
    "\n",
    "\n",
    "# ---------------- Helper Functions ----------------\n",
    "def distance_to_pixel(d_m):\n",
    "    return MARGIN_X + d_m * PIXELS_PER_M\n",
    "\n",
    "\n",
    "def stop_index_to_distance(i):\n",
    "    return i * DIST_BETWEEN_STOPS_M\n",
    "\n",
    "\n",
    "def find_next_stop_index(distance_m):\n",
    "    if distance_m >= TOTAL_ROUTE_M:\n",
    "        return NUM_STOPS - 1\n",
    "    idx = int(distance_m // DIST_BETWEEN_STOPS_M) + 1\n",
    "    return min(idx, NUM_STOPS - 1)\n",
    "\n",
    "\n",
    "def meters_to_time_min(meters, speed_kmph):\n",
    "    speed_mps = max(0.1, speed_kmph / 3.6)\n",
    "    return (meters / speed_mps) / 60.0\n",
    "\n",
    "\n",
    "# ---------------- Tkinter Display ----------------\n",
    "class BusDisplay(tk.Tk):\n",
    "    def __init__(self):\n",
    "        super().__init__()\n",
    "        self.title(\"IIT07 Bus Route Display\")\n",
    "        self.configure(bg=\"#101820\")\n",
    "        self.attributes(\"-fullscreen\", True)\n",
    "        self.bind(\"<Escape>\", lambda e: self.quit_app())\n",
    "\n",
    "        # --- Header ---\n",
    "        header = tk.Label(\n",
    "            self,\n",
    "            text=f\"🚌 {BUS_NAME} — IIT Roorkee → Devband Express\",\n",
    "            font=(\"Segoe UI\", 26, \"bold\"),\n",
    "            bg=\"#003f5c\",\n",
    "            fg=\"white\",\n",
    "            pady=15\n",
    "        )\n",
    "        header.pack(fill=\"x\")\n",
    "\n",
    "        # --- Info Bar ---\n",
    "        info_frame = tk.Frame(self, bg=\"#17202A\")\n",
    "        info_frame.pack(fill=\"x\")\n",
    "\n",
    "        self.lbl_speed = tk.Label(info_frame, text=f\"Speed: {BASE_SPEED_KMPH} km/h\", font=(\"Segoe UI\", 18, \"bold\"),\n",
    "                                  bg=\"#17202A\", fg=\"#00FF00\")\n",
    "        self.lbl_speed.pack(side=\"left\", padx=30)\n",
    "\n",
    "        # Speed control\n",
    "        tk.Label(info_frame, text=\"Adjust Speed:\", font=(\"Segoe UI\", 16), bg=\"#17202A\", fg=\"white\").pack(side=\"left\")\n",
    "        self.speed_var = tk.DoubleVar(value=BASE_SPEED_KMPH)\n",
    "        self.slider = ttk.Scale(info_frame, from_=50, to=200, orient=\"horizontal\", length=300,\n",
    "                                variable=self.speed_var, command=self.on_speed_change)\n",
    "        self.slider.pack(side=\"left\", padx=10)\n",
    "\n",
    "        # --- Canvas for route ---\n",
    "        self.canvas = tk.Canvas(self, width=CANVAS_W, height=CANVAS_H, bg=\"#101820\", highlightthickness=0)\n",
    "        self.canvas.pack(fill=\"both\", expand=True)\n",
    "\n",
    "        # --- Footer ---\n",
    "        self.footer = tk.Label(\n",
    "            self,\n",
    "            text=\"Press Esc to exit  |  IIT Roorkee Smart Transport Display Board\",\n",
    "            bg=\"#003f5c\",\n",
    "            fg=\"white\",\n",
    "            font=(\"Segoe UI\", 14)\n",
    "        )\n",
    "        self.footer.pack(fill=\"x\")\n",
    "\n",
    "        # --- Draw route and bus ---\n",
    "        self.draw_route()\n",
    "        self.create_bus()\n",
    "\n",
    "        self.last_time = time.time()\n",
    "        self.after(UPDATE_INTERVAL_MS, self.update_loop)\n",
    "\n",
    "    # ---------------- Draw Route ----------------\n",
    "    def draw_route(self):\n",
    "        self.stop_positions = []\n",
    "        x1 = MARGIN_X\n",
    "        x2 = MARGIN_X + PIXEL_ROUTE_LENGTH\n",
    "        self.canvas.create_line(x1, LINE_Y, x2, LINE_Y, fill=\"#00FFFF\", width=6)\n",
    "\n",
    "        colors = [\"#FF6F61\", \"#F7B801\", \"#6A0572\", \"#2EC4B6\", \"#FF8C42\",\n",
    "                  \"#8D99AE\", \"#00C49A\", \"#F94144\", \"#F3722C\", \"#43AA8B\"]\n",
    "\n",
    "        for i, name in enumerate(STOP_NAMES):\n",
    "            d = stop_index_to_distance(i)\n",
    "            x = distance_to_pixel(d)\n",
    "            self.stop_positions.append(x)\n",
    "            color = colors[i % len(colors)]\n",
    "            self.canvas.create_oval(\n",
    "                x - DOT_RADIUS, LINE_Y - DOT_RADIUS, x + DOT_RADIUS, LINE_Y + DOT_RADIUS,\n",
    "                fill=color, outline=\"white\", width=2\n",
    "            )\n",
    "            self.canvas.create_text(\n",
    "                x, LABEL_Y, text=name, fill=\"white\", font=(\"Segoe UI\", 10, \"bold\"), anchor=\"n\"\n",
    "            )\n",
    "\n",
    "    def create_bus(self):\n",
    "        px = distance_to_pixel(bus[\"distance_m\"])\n",
    "        by = LINE_Y - 50\n",
    "\n",
    "        # Bus body\n",
    "        self.bus_body = self.canvas.create_rectangle(px - 40, by - 22, px + 40, by + 22, fill=\"#FFD700\", outline=\"#DAA520\", width=3)\n",
    "        # Bus window\n",
    "        self.bus_window = self.canvas.create_rectangle(px - 28, by - 12, px + 28, by + 2, fill=\"#2E86C1\", outline=\"#17202A\")\n",
    "        # Bus number inside\n",
    "        self.bus_text = self.canvas.create_text(px, by + 5, text=\"IIT07\", font=(\"Segoe UI\", 14, \"bold\"), fill=\"black\")\n",
    "\n",
    "    # ---------------- Update ----------------\n",
    "    def update_loop(self):\n",
    "        now = time.time()\n",
    "        dt = now - self.last_time\n",
    "        self.last_time = now\n",
    "\n",
    "        if not bus[\"paused\"]:\n",
    "            bus[\"distance_m\"] += (bus[\"speed_kmph\"] / 3.6) * dt\n",
    "            if bus[\"distance_m\"] >= TOTAL_ROUTE_M:\n",
    "                bus[\"distance_m\"] = 0.0  # Loop back to start\n",
    "\n",
    "        self.update_bus_graphics()\n",
    "        self.update_info()\n",
    "        self.after(UPDATE_INTERVAL_MS, self.update_loop)\n",
    "\n",
    "    def update_bus_graphics(self):\n",
    "        px = distance_to_pixel(bus[\"distance_m\"])\n",
    "        by = LINE_Y - 50\n",
    "        self.canvas.coords(self.bus_body, px - 40, by - 22, px + 40, by + 22)\n",
    "        self.canvas.coords(self.bus_window, px - 28, by - 12, px + 28, by + 2)\n",
    "        self.canvas.coords(self.bus_text, px, by + 5)\n",
    "\n",
    "    def update_info(self):\n",
    "        next_idx = find_next_stop_index(bus[\"distance_m\"])\n",
    "        next_stop = STOP_NAMES[next_idx]\n",
    "        dist_m = stop_index_to_distance(next_idx) - bus[\"distance_m\"]\n",
    "        if dist_m < 0:\n",
    "            dist_m = 0\n",
    "        eta = meters_to_time_min(dist_m, bus[\"speed_kmph\"])\n",
    "\n",
    "        self.lbl_speed.config(text=f\"Speed: {bus['speed_kmph']:.0f} km/h\")\n",
    "\n",
    "        # Remove old ETA labels\n",
    "        self.canvas.delete(\"eta_text\")\n",
    "        hx = self.stop_positions[next_idx]\n",
    "        # ETA text near next stop\n",
    "        self.canvas.create_text(\n",
    "            hx, LINE_Y - 70, text=f\"ETA: {eta:.1f} min\",\n",
    "            fill=\"#FFD700\", font=(\"Segoe UI\", 12, \"bold\"), tag=\"eta_text\"\n",
    "        )\n",
    "\n",
    "        # Highlight current stop\n",
    "        self.canvas.delete(\"highlight\")\n",
    "        self.canvas.create_oval(\n",
    "            hx - DOT_RADIUS - 6, LINE_Y - DOT_RADIUS - 6,\n",
    "            hx + DOT_RADIUS + 6, LINE_Y + DOT_RADIUS + 6,\n",
    "            outline=\"#FFFF00\", width=3, tag=\"highlight\"\n",
    "        )\n",
    "\n",
    "    def on_speed_change(self, _=None):\n",
    "        bus[\"speed_kmph\"] = self.speed_var.get()\n",
    "\n",
    "    def quit_app(self):\n",
    "        self.destroy()\n",
    "\n",
    "\n",
    "# ---------------- Run ----------------\n",
    "if __name__ == \"__main__\":\n",
    "    app = BusDisplay()\n",
    "    app.mainloop()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "d312a881-804f-4780-a560-474b3e691a38",
   "metadata": {},
   "outputs": [],
   "source": [
    "#!/usr/bin/env python3\n",
    "\"\"\"\n",
    "IIT07 Bus Route Display — Interactive, colorful simulation\n",
    "\"\"\"\n",
    "\n",
    "import tkinter as tk\n",
    "from tkinter import ttk\n",
    "import time\n",
    "import math\n",
    "\n",
    "# ---------------- Configuration ----------------\n",
    "BUS_NAME = \"Bus IIT07\"\n",
    "STOP_NAMES = [\n",
    "    \"IIT MGCL Library\",\n",
    "    \"IIT Century Gate\",\n",
    "    \"Roorkee Bus Stand\",\n",
    "    \"SDM Chauk\",\n",
    "    \"Cownpore Chauk\",\n",
    "    \"Delhi Road\",\n",
    "    \"APJ Chauk\",\n",
    "    \"Manglaur Bus Stop\",\n",
    "    \"Upper Ganga Bridge\",\n",
    "    \"Devband\"\n",
    "]\n",
    "\n",
    "# Visual layout\n",
    "CANVAS_W = 1920\n",
    "CANVAS_H = 500\n",
    "MARGIN_X = 100\n",
    "LINE_Y = 250\n",
    "DOT_RADIUS = 12\n",
    "LABEL_Y = LINE_Y + 35\n",
    "\n",
    "# Route details\n",
    "DIST_BETWEEN_STOPS_M = 2000  # 2 km\n",
    "NUM_STOPS = len(STOP_NAMES)\n",
    "TOTAL_ROUTE_M = DIST_BETWEEN_STOPS_M * (NUM_STOPS - 1)\n",
    "\n",
    "# Simulation parameters\n",
    "BASE_SPEED_KMPH = 120.0\n",
    "UPDATE_INTERVAL_MS = 40\n",
    "\n",
    "PIXEL_ROUTE_LENGTH = CANVAS_W - 2 * MARGIN_X\n",
    "PIXELS_PER_M = PIXEL_ROUTE_LENGTH / TOTAL_ROUTE_M\n",
    "\n",
    "# ---------------- Bus State ----------------\n",
    "bus = {\n",
    "    \"distance_m\": 0.0,\n",
    "    \"speed_kmph\": BASE_SPEED_KMPH,\n",
    "    \"paused\": False,\n",
    "}\n",
    "\n",
    "\n",
    "# ---------------- Helper Functions ----------------\n",
    "def distance_to_pixel(d_m):\n",
    "    \"\"\"Converts distance in meters to canvas pixel coordinate.\"\"\"\n",
    "    return MARGIN_X + d_m * PIXELS_PER_M\n",
    "\n",
    "\n",
    "def stop_index_to_distance(i):\n",
    "    \"\"\"Calculates the distance (m) of a stop from the origin.\"\"\"\n",
    "    return i * DIST_BETWEEN_STOPS_M\n",
    "\n",
    "\n",
    "def find_next_stop_index(distance_m):\n",
    "    \"\"\"Determines the index of the next upcoming stop.\"\"\"\n",
    "    if distance_m >= TOTAL_ROUTE_M:\n",
    "        return NUM_STOPS - 1\n",
    "    idx = int(distance_m // DIST_BETWEEN_STOPS_M) + 1\n",
    "    return min(idx, NUM_STOPS - 1)\n",
    "\n",
    "\n",
    "def meters_to_time_min(meters, speed_kmph):\n",
    "    \"\"\"Calculates Estimated Time of Arrival (ETA) in minutes.\"\"\"\n",
    "    speed_mps = max(0.1, speed_kmph / 3.6)\n",
    "    return (meters / speed_mps) / 60.0\n",
    "\n",
    "\n",
    "# ---------------- Tkinter Display ----------------\n",
    "class BusDisplay(tk.Tk):\n",
    "    def __init__(self):\n",
    "        super().__init__()\n",
    "        self.title(\"IIT07 Bus Route Display\")\n",
    "        self.configure(bg=\"#101820\")\n",
    "        self.attributes(\"-fullscreen\", True)\n",
    "        self.bind(\"<Escape>\", lambda e: self.quit_app())\n",
    "\n",
    "        # --- Header ---\n",
    "        header = tk.Label(\n",
    "            self,\n",
    "            text=f\"🚌 {BUS_NAME} — IIT Roorkee → Devband Express\",\n",
    "            font=(\"Segoe UI\", 26, \"bold\"),\n",
    "            bg=\"#003f5c\",\n",
    "            fg=\"white\",\n",
    "            pady=15\n",
    "        )\n",
    "        header.pack(fill=\"x\")\n",
    "\n",
    "        # --- Info Bar ---\n",
    "        info_frame = tk.Frame(self, bg=\"#17202A\")\n",
    "        info_frame.pack(fill=\"x\")\n",
    "\n",
    "        self.lbl_speed = tk.Label(info_frame, text=f\"Speed: {BASE_SPEED_KMPH} km/h\", font=(\"Segoe UI\", 18, \"bold\"),\n",
    "                                     bg=\"#17202A\", fg=\"#00FF00\")\n",
    "        self.lbl_speed.pack(side=\"left\", padx=30)\n",
    "\n",
    "        # Speed control\n",
    "        tk.Label(info_frame, text=\"Adjust Speed:\", font=(\"Segoe UI\", 16), bg=\"#17202A\", fg=\"white\").pack(side=\"left\")\n",
    "        self.speed_var = tk.DoubleVar(value=BASE_SPEED_KMPH)\n",
    "        self.slider = ttk.Scale(info_frame, from_=50, to=200, orient=\"horizontal\", length=300,\n",
    "                                 variable=self.speed_var, command=self.on_speed_change)\n",
    "        self.slider.pack(side=\"left\", padx=10)\n",
    "\n",
    "        # --- Canvas for route ---\n",
    "        self.canvas = tk.Canvas(self, width=CANVAS_W, height=CANVAS_H, bg=\"#101820\", highlightthickness=0)\n",
    "        self.canvas.pack(fill=\"both\", expand=True)\n",
    "\n",
    "        # --- Footer ---\n",
    "        self.footer = tk.Label(\n",
    "            self,\n",
    "            text=\"Press Esc to exit | IIT Roorkee Smart Transport Display Board\",\n",
    "            bg=\"#003f5c\",\n",
    "            fg=\"white\",\n",
    "            font=(\"Segoe UI\", 14)\n",
    "        )\n",
    "        self.footer.pack(fill=\"x\")\n",
    "\n",
    "        # --- Draw route and bus ---\n",
    "        self.draw_route()\n",
    "        self.create_bus()\n",
    "\n",
    "        self.last_time = time.time()\n",
    "        self.after(UPDATE_INTERVAL_MS, self.update_loop)\n",
    "\n",
    "    # ---------------- Draw Route ----------------\n",
    "    def draw_route(self):\n",
    "        self.stop_positions = []\n",
    "        x1 = MARGIN_X\n",
    "        x2 = MARGIN_X + PIXEL_ROUTE_LENGTH\n",
    "        \n",
    "        # Main route line\n",
    "        self.canvas.create_line(x1, LINE_Y, x2, LINE_Y, fill=\"#00FFFF\", width=6)\n",
    "\n",
    "        colors = [\"#FF6F61\", \"#F7B801\", \"#6A0572\", \"#2EC4B6\", \"#FF8C42\",\n",
    "                  \"#8D99AE\", \"#00C49A\", \"#F94144\", \"#F3722C\", \"#43AA8B\"]\n",
    "\n",
    "        for i, name in enumerate(STOP_NAMES):\n",
    "            d = stop_index_to_distance(i)\n",
    "            x = distance_to_pixel(d)\n",
    "            self.stop_positions.append(x)\n",
    "            color = colors[i % len(colors)]\n",
    "            self.canvas.create_oval(\n",
    "                x - DOT_RADIUS, LINE_Y - DOT_RADIUS, x + DOT_RADIUS, LINE_Y + DOT_RADIUS,\n",
    "                fill=color, outline=\"white\", width=2\n",
    "            )\n",
    "            self.canvas.create_text(\n",
    "                x, LABEL_Y, text=name, fill=\"white\", font=(\"Segoe UI\", 10, \"bold\"), anchor=\"n\"\n",
    "            )\n",
    "\n",
    "    def create_bus(self):\n",
    "        px = distance_to_pixel(bus[\"distance_m\"])\n",
    "        by = LINE_Y  # Reference point (ground line)\n",
    "\n",
    "        # Bus dimensions and style inspired by the red bus image\n",
    "        W = 85  # Width\n",
    "        H = 40  # Height of body\n",
    "        \n",
    "        bus_y_top = by - H - 5 # 5 pixel gap above line for wheels\n",
    "        bus_y_bottom = by - 5\n",
    "        \n",
    "        # 1. Bus Body (Red color with rounded corners)\n",
    "        self.bus_body = self.canvas.create_rectangle(\n",
    "            px - W/2, bus_y_top, px + W/2, bus_y_bottom, \n",
    "            fill=\"#E74C3C\", outline=\"#C0392B\", width=2, tags=\"bus_parts\"\n",
    "        )\n",
    "        \n",
    "        # 2. Windows (Simplified rectangular windows)\n",
    "        window_height = 15\n",
    "        window_y = bus_y_top + 5\n",
    "        window_fill = \"#87CEEB\"\n",
    "        \n",
    "        self.windows = [\n",
    "            # Front Window (wider)\n",
    "            self.canvas.create_rectangle(px + 5, window_y, px + W/2 - 5, window_y + window_height, fill=window_fill, outline=\"#C0392B\", tags=\"bus_parts\"),\n",
    "            # Middle Window\n",
    "            self.canvas.create_rectangle(px - 15, window_y, px + 5, window_y + window_height, fill=window_fill, outline=\"#C0392B\", tags=\"bus_parts\"),\n",
    "            # Rear Window\n",
    "            self.canvas.create_rectangle(px - W/2 + 5, window_y, px - 15, window_y + window_height, fill=window_fill, outline=\"#C0392B\", tags=\"bus_parts\"),\n",
    "        ]\n",
    "\n",
    "        # 3. Wheels (Circles sitting just below the body)\n",
    "        wheel_radius = 8\n",
    "        wheel_y_center = by - 5\n",
    "        \n",
    "        self.wheel1 = self.canvas.create_oval(\n",
    "            px - 30 - wheel_radius, wheel_y_center - wheel_radius, \n",
    "            px - 30 + wheel_radius, wheel_y_center + wheel_radius, \n",
    "            fill=\"#333333\", outline=\"black\", tags=\"bus_parts\"\n",
    "        )\n",
    "        self.wheel2 = self.canvas.create_oval(\n",
    "            px + 25 - wheel_radius, wheel_y_center - wheel_radius, \n",
    "            px + 25 + wheel_radius, wheel_y_center + wheel_radius, \n",
    "            fill=\"#333333\", outline=\"black\", tags=\"bus_parts\"\n",
    "        )\n",
    "\n",
    "        # 4. Bus Number Text (Above the bus body)\n",
    "        text_y = bus_y_top - 12\n",
    "        self.bus_text = self.canvas.create_text(\n",
    "            px, text_y, \n",
    "            text=BUS_NAME.split(\" \")[1], # Just \"IIT07\"\n",
    "            font=(\"Segoe UI\", 12, \"bold\"), \n",
    "            fill=\"#FFD700\", \n",
    "            tags=\"bus_parts\"\n",
    "        )\n",
    "\n",
    "    # ---------------- Update ----------------\n",
    "    def update_loop(self):\n",
    "        now = time.time()\n",
    "        dt = now - self.last_time\n",
    "        self.last_time = now\n",
    "\n",
    "        if not bus[\"paused\"]:\n",
    "            bus[\"distance_m\"] += (bus[\"speed_kmph\"] / 3.6) * dt\n",
    "            if bus[\"distance_m\"] >= TOTAL_ROUTE_M:\n",
    "                bus[\"distance_m\"] = 0.0  # Loop back to start\n",
    "\n",
    "        self.update_bus_graphics()\n",
    "        self.update_info()\n",
    "        self.after(UPDATE_INTERVAL_MS, self.update_loop)\n",
    "\n",
    "    def update_bus_graphics(self):\n",
    "        px = distance_to_pixel(bus[\"distance_m\"])\n",
    "        by = LINE_Y\n",
    "        W = 85\n",
    "        H = 40\n",
    "        \n",
    "        bus_y_top = by - H - 5 \n",
    "        bus_y_bottom = by - 5\n",
    "        window_height = 15\n",
    "        window_y = bus_y_top + 5\n",
    "        wheel_radius = 8\n",
    "        wheel_y_center = by - 5\n",
    "        text_y = bus_y_top - 12\n",
    "\n",
    "        # Update bus body coordinates\n",
    "        self.canvas.coords(self.bus_body, px - W/2, bus_y_top, px + W/2, bus_y_bottom)\n",
    "        \n",
    "        # Update windows\n",
    "        self.canvas.coords(self.windows[0], px + 5, window_y, px + W/2 - 5, window_y + window_height)\n",
    "        self.canvas.coords(self.windows[1], px - 15, window_y, px + 5, window_y + window_height)\n",
    "        self.canvas.coords(self.windows[2], px - W/2 + 5, window_y, px - 15, window_y + window_height)\n",
    "\n",
    "        # Update wheels\n",
    "        self.canvas.coords(self.wheel1, \n",
    "            px - 30 - wheel_radius, wheel_y_center - wheel_radius, \n",
    "            px - 30 + wheel_radius, wheel_y_center + wheel_radius)\n",
    "        self.canvas.coords(self.wheel2, \n",
    "            px + 25 - wheel_radius, wheel_y_center - wheel_radius, \n",
    "            px + 25 + wheel_radius, wheel_y_center + wheel_radius)\n",
    "\n",
    "        # Update bus number text\n",
    "        self.canvas.coords(self.bus_text, px, text_y)\n",
    "\n",
    "    def update_info(self):\n",
    "        next_idx = find_next_stop_index(bus[\"distance_m\"])\n",
    "        \n",
    "        dist_m = stop_index_to_distance(next_idx) - bus[\"distance_m\"]\n",
    "        \n",
    "        # Handle distance wrapping/completion\n",
    "        if dist_m < 0:\n",
    "            dist_m = 0\n",
    "\n",
    "        eta = meters_to_time_min(dist_m, bus[\"speed_kmph\"])\n",
    "\n",
    "        self.lbl_speed.config(text=f\"Speed: {bus['speed_kmph']:.0f} km/h\")\n",
    "\n",
    "        # --- ETA Logic for Display ---\n",
    "        if dist_m < 50 and next_idx == NUM_STOPS - 1:\n",
    "            display_eta = \"Arrived\"\n",
    "        elif dist_m < 50:\n",
    "             display_eta = \"Arriving...\"\n",
    "        else:\n",
    "             display_eta = f\"{eta:.1f} min\"\n",
    "\n",
    "\n",
    "        # Remove old ETA labels\n",
    "        self.canvas.delete(\"eta_text\")\n",
    "        self.canvas.delete(\"highlight\")\n",
    "        \n",
    "        hx = self.stop_positions[next_idx]\n",
    "\n",
    "        # 1. Draw Stop Highlight (yellow ring)\n",
    "        self.canvas.create_oval(\n",
    "            hx - DOT_RADIUS - 6, LINE_Y - DOT_RADIUS - 6,\n",
    "            hx + DOT_RADIUS + 6, LINE_Y + DOT_RADIUS + 6,\n",
    "            outline=\"#FFFF00\", width=3, tag=\"highlight\"\n",
    "        )\n",
    "        \n",
    "        # 2. Display ETA on the Next Stop\n",
    "        self.canvas.create_text(\n",
    "            hx, LINE_Y - 50, # Position above the stop dot\n",
    "            text=f\"ETA: {display_eta}\",\n",
    "            fill=\"#FFD700\", \n",
    "            font=(\"Segoe UI\", 12, \"bold\"),\n",
    "            tag=\"eta_text\"\n",
    "        )\n",
    "\n",
    "    def on_speed_change(self, _=None):\n",
    "        bus[\"speed_kmph\"] = self.speed_var.get()\n",
    "\n",
    "    def quit_app(self):\n",
    "        self.destroy()\n",
    "\n",
    "\n",
    "# ---------------- Run ----------------\n",
    "if __name__ == \"__main__\":\n",
    "    app = BusDisplay()\n",
    "    app.mainloop()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "4cb3c5a4-bba7-4165-a5bd-65bc100d8141",
   "metadata": {},
   "outputs": [],
   "source": [
    "#!/usr/bin/env python3\n",
    "\"\"\"\n",
    "IIT07 Bus Route Display — Interactive, colorful simulation\n",
    "\"\"\"\n",
    "\n",
    "import tkinter as tk\n",
    "from tkinter import ttk\n",
    "import time\n",
    "import math\n",
    "\n",
    "# ---------------- Configuration ----------------\n",
    "BUS_NAME = \"Bus IIT07\"\n",
    "STOP_NAMES = [\n",
    "    \"IIT MGCL Library\",\n",
    "    \"IIT Century Gate\",\n",
    "    \"Roorkee Bus Stand\",\n",
    "    \"SDM Chauk\",\n",
    "    \"Cownpore Chauk\",\n",
    "    \"Delhi Road\",\n",
    "    \"APJ Chauk\",\n",
    "    \"Manglaur Bus Stop\",\n",
    "    \"Upper Ganga Bridge\",\n",
    "    \"Devband\"\n",
    "]\n",
    "\n",
    "# Visual layout\n",
    "CANVAS_W = 1920\n",
    "CANVAS_H = 500\n",
    "MARGIN_X = 100\n",
    "LINE_Y = 250\n",
    "DOT_RADIUS = 12\n",
    "LABEL_Y = LINE_Y + 35\n",
    "\n",
    "# Route details\n",
    "DIST_BETWEEN_STOPS_M = 2000  # 2 km\n",
    "NUM_STOPS = len(STOP_NAMES)\n",
    "TOTAL_ROUTE_M = DIST_BETWEEN_STOPS_M * (NUM_STOPS - 1)\n",
    "\n",
    "# Simulation parameters\n",
    "BASE_SPEED_KMPH = 120.0\n",
    "UPDATE_INTERVAL_MS = 40\n",
    "\n",
    "PIXEL_ROUTE_LENGTH = CANVAS_W - 2 * MARGIN_X\n",
    "PIXELS_PER_M = PIXEL_ROUTE_LENGTH / TOTAL_ROUTE_M\n",
    "\n",
    "# Color Configuration\n",
    "COVERED_COLOR = \"#FF0000\"  # Red for covered distance\n",
    "REMAINING_COLOR = \"#00FF00\"  # Green for remaining distance\n",
    "\n",
    "# ---------------- Bus State ----------------\n",
    "bus = {\n",
    "    \"distance_m\": 0.0,\n",
    "    \"speed_kmph\": BASE_SPEED_KMPH,\n",
    "    \"paused\": False,\n",
    "    \"blink_state\": True # For blinking effect\n",
    "}\n",
    "\n",
    "\n",
    "# ---------------- Helper Functions ----------------\n",
    "def distance_to_pixel(d_m):\n",
    "    \"\"\"Converts distance in meters to canvas pixel coordinate.\"\"\"\n",
    "    return MARGIN_X + d_m * PIXELS_PER_M\n",
    "\n",
    "\n",
    "def stop_index_to_distance(i):\n",
    "    \"\"\"Calculates the distance (m) of a stop from the origin.\"\"\"\n",
    "    return i * DIST_BETWEEN_STOPS_M\n",
    "\n",
    "\n",
    "def find_next_stop_index(distance_m):\n",
    "    \"\"\"Determines the index of the next upcoming stop.\"\"\"\n",
    "    if distance_m >= TOTAL_ROUTE_M:\n",
    "        return NUM_STOPS - 1\n",
    "    idx = int(distance_m // DIST_BETWEEN_STOPS_M) + 1\n",
    "    return min(idx, NUM_STOPS - 1)\n",
    "\n",
    "\n",
    "def meters_to_time_min(meters, speed_kmph):\n",
    "    \"\"\"Calculates Estimated Time of Arrival (ETA) in minutes.\"\"\"\n",
    "    speed_mps = max(0.1, speed_kmph / 3.6)\n",
    "    return (meters / speed_mps) / 60.0\n",
    "\n",
    "\n",
    "# ---------------- Tkinter Display ----------------\n",
    "class BusDisplay(tk.Tk):\n",
    "    def __init__(self):\n",
    "        super().__init__()\n",
    "        self.title(\"IIT07 Bus Route Display\")\n",
    "        self.configure(bg=\"#101820\")\n",
    "        self.attributes(\"-fullscreen\", True)\n",
    "        self.bind(\"<Escape>\", lambda e: self.quit_app())\n",
    "\n",
    "        # --- Header ---\n",
    "        header = tk.Label(\n",
    "            self,\n",
    "            text=f\"🚌 {BUS_NAME} — IIT Roorkee → Devband Express\",\n",
    "            font=(\"Segoe UI\", 26, \"bold\"),\n",
    "            bg=\"#003f5c\",\n",
    "            fg=\"white\",\n",
    "            pady=15\n",
    "        )\n",
    "        header.pack(fill=\"x\")\n",
    "\n",
    "        # --- Info Bar ---\n",
    "        info_frame = tk.Frame(self, bg=\"#17202A\")\n",
    "        info_frame.pack(fill=\"x\")\n",
    "\n",
    "        self.lbl_speed = tk.Label(info_frame, text=f\"Speed: {BASE_SPEED_KMPH} km/h\", font=(\"Segoe UI\", 18, \"bold\"),\n",
    "                                     bg=\"#17202A\", fg=\"#00FF00\")\n",
    "        self.lbl_speed.pack(side=\"left\", padx=30)\n",
    "\n",
    "        # Speed control\n",
    "        tk.Label(info_frame, text=\"Adjust Speed:\", font=(\"Segoe UI\", 16), bg=\"#17202A\", fg=\"white\").pack(side=\"left\")\n",
    "        self.speed_var = tk.DoubleVar(value=BASE_SPEED_KMPH)\n",
    "        self.slider = ttk.Scale(info_frame, from_=50, to=200, orient=\"horizontal\", length=300,\n",
    "                                 variable=self.speed_var, command=self.on_speed_change)\n",
    "        self.slider.pack(side=\"left\", padx=10)\n",
    "\n",
    "        # --- Canvas for route ---\n",
    "        self.canvas = tk.Canvas(self, width=CANVAS_W, height=CANVAS_H, bg=\"#101820\", highlightthickness=0)\n",
    "        self.canvas.pack(fill=\"both\", expand=True)\n",
    "        \n",
    "        # Initialize route line segments (will be redrawn in update_route_line)\n",
    "        self.covered_line = self.canvas.create_line(MARGIN_X, LINE_Y, MARGIN_X, LINE_Y, fill=COVERED_COLOR, width=6, tags=\"route_line\")\n",
    "        self.remaining_line = self.canvas.create_line(MARGIN_X, LINE_Y, MARGIN_X + PIXEL_ROUTE_LENGTH, LINE_Y, fill=REMAINING_COLOR, width=6, tags=\"route_line\")\n",
    "\n",
    "\n",
    "        # --- Footer ---\n",
    "        self.footer = tk.Label(\n",
    "            self,\n",
    "            text=\"Press Esc to exit | IIT Roorkee Smart Transport Display Board\",\n",
    "            bg=\"#003f5c\",\n",
    "            fg=\"white\",\n",
    "            font=(\"Segoe UI\", 14)\n",
    "        )\n",
    "        self.footer.pack(fill=\"x\")\n",
    "\n",
    "        # --- Draw route and bus ---\n",
    "        self.draw_route_stops() # Only draws the dots and labels\n",
    "        self.create_bus()\n",
    "\n",
    "        self.last_time = time.time()\n",
    "        self.after(UPDATE_INTERVAL_MS, self.update_loop)\n",
    "        self.after(250, self.blink_next_stop) # Start blinking every 250ms\n",
    "\n",
    "    # ---------------- Draw Route ----------------\n",
    "    def draw_route_stops(self):\n",
    "        \"\"\"Draws the fixed stop dots and labels.\"\"\"\n",
    "        self.stop_positions = []\n",
    "        \n",
    "        colors = [\"#FF6F61\", \"#F7B801\", \"#6A0572\", \"#2EC4B6\", \"#FF8C42\",\n",
    "                  \"#8D99AE\", \"#00C49A\", \"#F94144\", \"#F3722C\", \"#43AA8B\"]\n",
    "\n",
    "        for i, name in enumerate(STOP_NAMES):\n",
    "            d = stop_index_to_distance(i)\n",
    "            x = distance_to_pixel(d)\n",
    "            self.stop_positions.append(x)\n",
    "            color = colors[i % len(colors)]\n",
    "            \n",
    "            # Create the stop dot, tagging it with its index\n",
    "            self.canvas.create_oval(\n",
    "                x - DOT_RADIUS, LINE_Y - DOT_RADIUS, x + DOT_RADIUS, LINE_Y + DOT_RADIUS,\n",
    "                fill=color, outline=\"white\", width=2, tags=(f\"stop_dot_{i}\", \"stop_dots\")\n",
    "            )\n",
    "            # Create the stop label\n",
    "            self.canvas.create_text(\n",
    "                x, LABEL_Y, text=name, fill=\"white\", font=(\"Segoe UI\", 10, \"bold\"), anchor=\"n\", tags=\"stop_labels\"\n",
    "            )\n",
    "\n",
    "    def create_bus(self):\n",
    "        px = distance_to_pixel(bus[\"distance_m\"])\n",
    "        by = LINE_Y  # Reference point (ground line)\n",
    "\n",
    "        # Bus dimensions and style (reusing the logic from the user's latest file)\n",
    "        W = 85\n",
    "        H = 40\n",
    "        bus_y_top = by - H - 5\n",
    "        bus_y_bottom = by - 5\n",
    "        window_height = 15\n",
    "        window_y = bus_y_top + 5\n",
    "        wheel_radius = 8\n",
    "        wheel_y_center = by - 5\n",
    "        text_y = bus_y_top - 12\n",
    "        \n",
    "        # 1. Bus Body \n",
    "        self.bus_body = self.canvas.create_rectangle(\n",
    "            px - W/2, bus_y_top, px + W/2, bus_y_bottom, \n",
    "            fill=\"#E74C3C\", outline=\"#C0392B\", width=2, tags=\"bus_parts\"\n",
    "        )\n",
    "        \n",
    "        # 2. Windows \n",
    "        self.windows = [\n",
    "            self.canvas.create_rectangle(px + 5, window_y, px + W/2 - 5, window_y + window_height, fill=\"#87CEEB\", outline=\"#C0392B\", tags=\"bus_parts\"),\n",
    "            self.canvas.create_rectangle(px - 15, window_y, px + 5, window_y + window_height, fill=\"#87CEEB\", outline=\"#C0392B\", tags=\"bus_parts\"),\n",
    "            self.canvas.create_rectangle(px - W/2 + 5, window_y, px - 15, window_y + window_height, fill=\"#87CEEB\", outline=\"#C0392B\", tags=\"bus_parts\"),\n",
    "        ]\n",
    "\n",
    "        # 3. Wheels \n",
    "        self.wheel1 = self.canvas.create_oval(\n",
    "            px - 30 - wheel_radius, wheel_y_center - wheel_radius, \n",
    "            px - 30 + wheel_radius, wheel_y_center + wheel_radius, \n",
    "            fill=\"#333333\", outline=\"black\", tags=\"bus_parts\"\n",
    "        )\n",
    "        self.wheel2 = self.canvas.create_oval(\n",
    "            px + 25 - wheel_radius, wheel_y_center - wheel_radius, \n",
    "            px + 25 + wheel_radius, wheel_y_center + wheel_radius, \n",
    "            fill=\"#333333\", outline=\"black\", tags=\"bus_parts\"\n",
    "        )\n",
    "\n",
    "        # 4. Bus Number Text \n",
    "        self.bus_text = self.canvas.create_text(\n",
    "            px, text_y, \n",
    "            text=BUS_NAME.split(\" \")[1],\n",
    "            font=(\"Segoe UI\", 12, \"bold\"), \n",
    "            fill=\"#FFD700\", \n",
    "            tags=\"bus_parts\"\n",
    "        )\n",
    "\n",
    "    # ---------------- Route Line Update ----------------\n",
    "    def update_route_line(self, px):\n",
    "        \"\"\"Redraws the route line segments based on bus position.\"\"\"\n",
    "        \n",
    "        # Covered distance (Red) from start (MARGIN_X) to current bus position (px)\n",
    "        self.canvas.coords(self.covered_line, MARGIN_X, LINE_Y, px, LINE_Y)\n",
    "        self.canvas.itemconfig(self.covered_line, fill=COVERED_COLOR, width=6)\n",
    "        \n",
    "        # Remaining distance (Green) from current bus position (px) to end (MARGIN_X + PIXEL_ROUTE_LENGTH)\n",
    "        self.canvas.coords(self.remaining_line, px, LINE_Y, MARGIN_X + PIXEL_ROUTE_LENGTH, LINE_Y)\n",
    "        self.canvas.itemconfig(self.remaining_line, fill=REMAINING_COLOR, width=6)\n",
    "\n",
    "    # ---------------- Blinking Stop Logic ----------------\n",
    "    def blink_next_stop(self):\n",
    "        \"\"\"Toggles the visibility of the next stop's highlight.\"\"\"\n",
    "        next_idx = find_next_stop_index(bus[\"distance_m\"])\n",
    "        hx = self.stop_positions[next_idx]\n",
    "        \n",
    "        # Remove old highlights first\n",
    "        self.canvas.delete(\"highlight\") \n",
    "        \n",
    "        if bus[\"blink_state\"]:\n",
    "            # Draw the highlight\n",
    "            self.canvas.create_oval(\n",
    "                hx - DOT_RADIUS - 6, LINE_Y - DOT_RADIUS - 6,\n",
    "                hx + DOT_RADIUS + 6, LINE_Y + DOT_RADIUS + 6,\n",
    "                outline=REMAINING_COLOR, width=3, tag=\"highlight\" # Blinking Green\n",
    "            )\n",
    "        \n",
    "        # Toggle state for next cycle\n",
    "        bus[\"blink_state\"] = not bus[\"blink_state\"]\n",
    "        \n",
    "        # Schedule the next blink\n",
    "        self.after(250, self.blink_next_stop)\n",
    "\n",
    "\n",
    "    # ---------------- Main Update Loop ----------------\n",
    "    def update_loop(self):\n",
    "        now = time.time()\n",
    "        dt = now - self.last_time\n",
    "        self.last_time = now\n",
    "\n",
    "        if not bus[\"paused\"]:\n",
    "            bus[\"distance_m\"] += (bus[\"speed_kmph\"] / 3.6) * dt\n",
    "            if bus[\"distance_m\"] >= TOTAL_ROUTE_M:\n",
    "                bus[\"distance_m\"] = 0.0  # Loop back to start\n",
    "\n",
    "        px = distance_to_pixel(bus[\"distance_m\"])\n",
    "        \n",
    "        self.update_bus_graphics(px)\n",
    "        self.update_route_line(px)\n",
    "        self.update_info()\n",
    "        \n",
    "        self.after(UPDATE_INTERVAL_MS, self.update_loop)\n",
    "\n",
    "    def update_bus_graphics(self, px):\n",
    "        by = LINE_Y\n",
    "        W = 85\n",
    "        H = 40\n",
    "        \n",
    "        bus_y_top = by - H - 5 \n",
    "        bus_y_bottom = by - 5\n",
    "        window_height = 15\n",
    "        window_y = bus_y_top + 5\n",
    "        wheel_radius = 8\n",
    "        wheel_y_center = by - 5\n",
    "        text_y = bus_y_top - 12\n",
    "\n",
    "        # Update bus body coordinates\n",
    "        # NOTE: This uses the original coordinates logic (from px, by) to redraw the bus parts\n",
    "        self.canvas.coords(self.bus_body, px - W/2, bus_y_top, px + W/2, bus_y_bottom)\n",
    "        self.canvas.coords(self.windows[0], px + 5, window_y, px + W/2 - 5, window_y + window_height)\n",
    "        self.canvas.coords(self.windows[1], px - 15, window_y, px + 5, window_y + window_height)\n",
    "        self.canvas.coords(self.windows[2], px - W/2 + 5, window_y, px - 15, window_y + window_height)\n",
    "        self.canvas.coords(self.wheel1, \n",
    "            px - 30 - wheel_radius, wheel_y_center - wheel_radius, \n",
    "            px - 30 + wheel_radius, wheel_y_center + wheel_radius)\n",
    "        self.canvas.coords(self.wheel2, \n",
    "            px + 25 - wheel_radius, wheel_y_center - wheel_radius, \n",
    "            px + 25 + wheel_radius, wheel_y_center + wheel_radius)\n",
    "        self.canvas.coords(self.bus_text, px, text_y)\n",
    "\n",
    "    def update_info(self):\n",
    "        next_idx = find_next_stop_index(bus[\"distance_m\"])\n",
    "        \n",
    "        dist_m = stop_index_to_distance(next_idx) - bus[\"distance_m\"]\n",
    "        \n",
    "        if dist_m < 0:\n",
    "            dist_m = 0\n",
    "\n",
    "        eta = meters_to_time_min(dist_m, bus[\"speed_kmph\"])\n",
    "\n",
    "        self.lbl_speed.config(text=f\"Speed: {bus['speed_kmph']:.0f} km/h\")\n",
    "\n",
    "        # --- ETA Logic for Display ---\n",
    "        if dist_m < 50 and next_idx == NUM_STOPS - 1:\n",
    "            display_eta = \"Arrived\"\n",
    "        elif dist_m < 50:\n",
    "             display_eta = \"Arriving...\"\n",
    "        else:\n",
    "             display_eta = f\"{eta:.1f} min\"\n",
    "\n",
    "\n",
    "        # Remove old ETA labels\n",
    "        self.canvas.delete(\"eta_text\")\n",
    "        \n",
    "        hx = self.stop_positions[next_idx]\n",
    "        \n",
    "        # Display ETA on the Next Stop\n",
    "        self.canvas.create_text(\n",
    "            hx, LINE_Y - 50, # Position above the stop dot\n",
    "            text=f\"ETA: {display_eta}\",\n",
    "            fill=\"#FFD700\", \n",
    "            font=(\"Segoe UI\", 12, \"bold\"),\n",
    "            tag=\"eta_text\"\n",
    "        )\n",
    "\n",
    "    def on_speed_change(self, _=None):\n",
    "        bus[\"speed_kmph\"] = self.speed_var.get()\n",
    "\n",
    "    def quit_app(self):\n",
    "        self.destroy()\n",
    "\n",
    "\n",
    "# ---------------- Run ----------------\n",
    "if __name__ == \"__main__\":\n",
    "    app = BusDisplay()\n",
    "    app.mainloop()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "76aba58e-d3b9-4c30-a406-9b7e50cfdbf6",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
